name: Build and Commit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm install
      - run: npm run build
      - run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com
          git add dist/
          if git commit -m "Update build" ; then
            git push origin HEAD:main
          fi
